<?php
/**
 * Created by PhpStorm.
 * User: debasis
 * Date: 16/6/15
 * Time: 12:04 AM
 */

function custome_register_user_init() // init function called by defaulted when this module loaded by system
{

    echo $GLOBALS['theme'];




}






function custome_register_user_form_altser(&$form, &$form_state, $form_id) {

   //var_dump($form);
    if($form_id=='user_register_form') {
       $form['actions']['submit']['#suffix']= "<div id='test-ajax'></div>";
       $form['actions']['submit']['#value']= 'Send';
      /* $form['actions']['submit']['#ajax']= array(*/
      /*     "callback" => "dr_search_test_form_callback3",*/
      /*     "wrapper" => "test-ajax",*/
      /*     "event" => "click",*/
      /*     "effect" => "fade",*/
      /*     "method" => "replace");*/

       //$form['#prefix']="<div id='test-ajax'></div>";


        //$form['account']['name']['#value']="hoi";
        $form['account']['name']['#suffix']="<div id='test-ajax'></div>";
        $form['account']['name']['#ajax']=array(
            "callback"=>"dr_search_test_form_callback",
            "wrapper" => "test-ajax-name",
            "event" => "blur"
        );
        $form['account']['mail']['#suffix']="<div id='test-ajax'></div>";
        $form['account']['mail']['#ajax']=array(
            "callback"=>"dr_search_test_form_callback3",
           "wrapper" => "test-ajax-mail",
           "event" => "blur"
       );

       //$form['user_first_name']['#access']=false;
       $form['field_last_name']['#ajax']=array(
           "callback"=>"dr_search_test_form_callback1",
           "wrapper" => "test-ajax",
           "event" => "blur",
           "method" => "replace"
       );
      // $form["#prefix"] = "<div id='test-ajax-name'></div>";
       //$form["name"] = array("#type" => "textfield", "#required" => true, "#title" => "Name");
       /*$form["submit"] = array(
           "#type" => "submit",
           "#value" => "Send",
           "#ajax" => array(
               "callback" => "dr_search_test_form_callback",
               "wrapper" => "test-ajax",
               "event" => "click",
               "effect" => "fade"));*/

   }






    return $form;
}

function dr_search_test_form_callback($form, &$fstate) {
    form_set_error("user_first_name", "Some error to display.");
    return "<div id='test-ajax-name'>?????</div>";
}

function dr_search_test_form_callback1($form, &$fstate) {
    form_set_error("user_first_name", "Some error to display.");
    return $form;
}

function dr_search_test_form_callback2($form, &$fstate) {
    return "<div id='test-ajax'>?????</div>";
}
function dr_search_test_form_callback3($form, &$fstate) {
    //var_dump(form_get_errors());
    $error=form_get_errors();
    if(isset($error['name']))
    return "<div id='test-ajax-name'>---".(@$error['name'])."</div>";
     if(isset($error['mail']))
     return "<div id='test-ajax-mail'>---".(@$error['mail'])."</div>";

    return "<div id='test-ajax'>?????</div><div id='test-ajax'>---".(@$error['name'])."</div>";
}

function dr_search_test_form_validate($form, &$fstate) {

    //var_dump($form);
    form_set_error("user_first_name", "Some error to display.");
}


function custome_register_user_enable()
{
    //echo 87;
// Check if our field is not already created.
    if (!field_info_field('user_first_name')) {

        // Create the field base.
        $field = array(
            'field_name' => 'user_first_name',
            'type' => 'text',
        );
        field_create_field($field);

        // Create the field instance on the bundle.
        $instance = array(
            'field_name' => 'user_first_name',
            'entity_type' => 'user',
            'label' => 'First Name',
            'bundle' => 'user',
            // If you don't set the "required" property then the field wont be required by default.
            'required' => TRUE,
            'settings' => array(
                // Here you inform either or not you want this field showing up on the registration form.
                'user_register_form' => 1,
            ),
            'widget' => array(
                'type' => 'textfield',
                'weight' => '-60',
            ),
        );
        field_create_instance($instance);
    }
}








function custome_register_user_disable() {

    if (field_info_field('user_first_name')) {

        // Create the field base.
        $field = array(
            'field_name' => 'user_first_name',
            'type' => 'text',
        );
        field_delete_field($field);
    }

}


