<?php
/**
 * Created by PhpStorm.
 * User: debasis
 * Date: 16/6/15
 * Time: 12:04 AM
 */

function custome_register_user_init() // init function called by defaulted when this module loaded by system
{

    echo $GLOBALS['theme'];




}


function custome_register_user_enable()
{
    //echo 87;
// Check if our field is not already created.
    if (!field_info_field('user_first_name')) {

        // Create the field base.
        $field = array(
            'field_name' => 'user_first_name',
            'type' => 'text',
        );
        field_create_field($field);

        // Create the field instance on the bundle.
        $instance = array(
            'field_name' => 'user_first_name',
            'entity_type' => 'user',
            'label' => 'First Name',
            'bundle' => 'user',
            // If you don't set the "required" property then the field wont be required by default.
            'required' => TRUE,
            'settings' => array(
                // Here you inform either or not you want this field showing up on the registration form.
                'user_register_form' => 1,
            ),
            'widget' => array(
                'type' => 'textfield',
                'weight' => '-60',
            ),
        );
        field_create_instance($instance);
    }
}








function custome_register_user_disable() {

    if (field_info_field('user_first_name')) {

        // Create the field base.
        $field = array(
            'field_name' => 'user_first_name',
            'type' => 'text',
        );
        field_delete_field($field);
    }

}


